version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package.zip search-photos.py
      - zip -r9 deployment_package2.zip index-photos.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://deployment_package.zip
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://deployment_package2.zip
      - echo "DONE!!"
